import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const cars = sqliteTable("cars", {
  id: text("id").primaryKey(),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  year: integer("year").notNull(),
  price: real("price").notNull(),
  mileage: integer("mileage").notNull(),
  transmission: text("transmission", { enum: ["Automatic", "Manual"] }).notNull(),
  fuelType: text("fuel_type", { enum: ["Gasoline", "Diesel", "Hybrid", "Electric", "LPG"] }).notNull(),
  engineTier: text("engine_tier"),
  engineVolume: text("engine_volume"),
  image: text("image").notNull(),
  images: text("images", { mode: "json" }).$type<string[]>(),
  auctionDate: text("auction_date").notNull(),
  lotNumber: text("lot_number").notNull(),
  location: text("location").notNull(),
  condition: text("condition", { enum: ["Excellent", "Good", "Fair"] }).notNull(),
  startingBid: real("starting_bid").notNull(),
  kcarId: text("kcar_id"),
  auctionCode: text("auction_code"),
  kcarStatus: text("kcar_status"),
  grade: text("grade"),
  exbitSeq: text("exbit_seq"),
  cno: text("cno"),
  firstRegDate: text("first_reg_date"),
  color: text("color"),
  vin: text("vin"),
  driveType: text("drive_type"),
  finalPrice: real("final_price"),
  soldStatus: text("sold_status"),
  inspectionData: text("inspection_data"),
  createdAt: text("created_at").notNull().default("(datetime('now'))"),
  updatedAt: text("updated_at"),
});

export const bidRequests = sqliteTable("bid_requests", {
  id: text("id").primaryKey(),
  carId: text("car_id").notNull().references(() => cars.id),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  maxBid: real("max_bid").notNull(),
  message: text("message"),
  ip: text("ip"),
  createdAt: text("created_at").notNull().default("(datetime('now'))"),
});
